### PR TITLE
Add alarm state & reset button

### PR DESCRIPTION
**Pull request by Robbe-B**
image

Dependency on https://github.com/Crisicus/maestro_mcz/pull/36

Note: 
When I intentionally let my stove run out of pellets, the alarm 'A2' shows up , trying to reset it with this functionality didn't work for me, this should work in theorie. It didn't worked with the MCZ App either. 
I'm not sure in which cases this can be used.
@Crisicus you know more about this ?

### CODE REVIEW

**Comment by Crisicus** [comment]
It was something I saw in the config and wanted to try out. Unfortunately it does nothing. I assume this is for internal testing or something. I tried the same you did (A2). I doubt it works for other codes.

**Comment by Robbe-B** [comment]
Oh, yeah, in that case we can maybe disable it by default 😄

**Comment by Robbe-B** [comment]
@Crisicus , I was kinda thinking maybe there are different types of alarms , some of them are remotely resettable, some of them are not, because manual interaction is needed, like filling up with pellets. 😄

**Comment by Crisicus** [comment]
I tried leaving the lid open aswel, but I guess that's also a "needs intervention" code.

**Comment by Robbe-B** [comment]
Indeed @Crisicus , we can merge this one I guess , but we'll need to re-evaluate if someone is actually able to use it, otherwise we disable it by default. 
If you would find some time to code review these pull requests, that would be cool.
Thanks for the quick responses 👍

**Comment by RickType** [comment]
Question: My understanding is there is an alarm when the stove is running "dry". In this case the stove will "fire" an alarm (and shut down). But there are also stove models with a dedicated sensor which warn the user when the pellet level is below a certain value (detected by the dedicated sensor). This gives the user some time to fill it up again.
I think I saw in the diagnostic file the State ""sens_liv_pellet": true / false,"

Is this covered in this feature request?

Thanks and keep up your good work
Patrick

Sensor needs to be puchased as an extra option, see:
https://www.wolf-online-shop.de/MCZ-Pellet-Fuellstandsensor-zur-Fuellstandermittlung-fuer-alle-Maestro-Geraete::264185.html

**Comment by Robbe-B** [comment]
@Crisicus, FYI, I found some documentation about this on a stove datasheet

**Comment by Robbe-B** [comment]
> Question: My understanding is there is an alarm when the stove is running "dry". In this case the stove will "fire" an alarm (and shut down). But there are also stove models with a dedicated sensor which warn the user when the pellet level is below a certain value (detected by the dedicated sensor). This gives the user some time to fill it up again. I think I saw in the diagnostic file the State ""sens_liv_pellet": true / false,"
> 
> Is this covered in this feature request?
> 
> Thanks and keep up your good work Patrick
> 
> Sensor needs to be puchased as an extra option, see: https://www.wolf-online-shop.de/MCZ-Pellet-Fuellstandsensor-zur-Fuellstandermittlung-fuer-alle-Maestro-Geraete::264185.html

Hi @RickType,
We are aware there are stoves with this sensor. 
Unfortunately, this is not covered by this pull request.
Does your stove model has such sensor ? 
If yes, how does it show up on the MCZ app ?

**Comment by RickType** [comment]
Sure, here you are...
"Pellets sind fast aufgebraucht" = "Pellet store is almost empty"
Screenshot_20230430_171505
Screenshot_20230430_171635

**Comment by Robbe-B** [comment]
@RickType,
Just out of curiosity, why is the room temp 0.0°C ?

**Comment by RickType** [comment]
I switched the senor (NTC 1) off. In the meanwhile I switched it on again.. see attached picture.
For me the room temperature has no relevance for the stove.
The stove is basically heating a 800 Liter buffer int he basement.
There are two NTC's in. NTC2 (Top) and NTC 3 (Middle).
Installation Set No. 6 means that the stove is heating the water until the temperature is reaching a desired temperature for NTC 2. I think it is currently set to 73 degrees Celsius.

**Comment by RickType** [comment]
Strange, I dissabled the integration and reactivated it again. Now it looks much better and I have two stoves in the inventory...????
EntityNew

**Comment by Robbe-B** [comment]
Nice to here it's better after reloading the integration. The 2nd stove might still be an issue. 
Would it be possible to send me the diagnostics file again , now that it's better ?

**Comment by RickType** [comment]
Sure, here u are..

[config_entry-maestro_mcz-a821c5f35691a9b3f5ac510aa401f211.json.txt](https://github.com/Crisicus/maestro_mcz/files/11361668/config_entry-maestro_mcz-a821c5f35691a9b3f5ac510aa401f211.json.txt)

**Comment by Robbe-B** [comment]
Thanks, are you able to remove the first (kinda not working) stove ?

**Comment by RickType** [comment]
Removing of a single stove was not working, therefore I deleted both and added the one that is working again.

**Comment by RickType** [comment]
Here is also the debug log... At least a bit of it...
[home-assistant_maestro_mcz_2023-04-30T15-54-07.856Z_New.log](https://github.com/Crisicus/maestro_mcz/files/11361688/home-assistant_maestro_mcz_2023-04-30T15-54-07.856Z_New.log)

**Comment by Robbe-B** [comment]
@RickType, 
Can you try installing [v0.3.1-beta](https://github.com/Crisicus/maestro_mcz/releases/tag/v0.3.1-beta) ?
See if this one still gives you issues in the logfiles 😄

**Comment by Crisicus** [comment]
> @RickType, 
> 
> Can you try installing [v0.3.1-beta](https://github.com/Crisicus/maestro_mcz/releases/tag/v0.3.1-beta) ?
> 
> See if this one still gives you issues in the logfiles 😄 

This was the double setup thing I was referring to earlier on the device info commit

**Comment by Robbe-B** [comment]
@Crisicus,
I did changed that device info method after your feedback. 
So I don't think there is something wrong with that. 
What I noticed in the diagnostics file (before the reload) is that the serial number was an empty string instead of 'redacted'. 
Could it be that the first time, the stove setup used an empty serial number as identifier, fixing this by reloading the integration. And therefore having 2 stoves showing up ?

**Comment by RickType** [comment]
Is the serial number the entry "UniqueCode"? From what I see it was never empty?
I will have a look into the diagnostic file and would issue a feature request for some of the missing parameters. Additionally I check the source code. Maybe there will we a PR from me in the next 1-2 weeks... ;-)

**Comment by Robbe-B** [comment]
@RickType,
Both fields are the serial number.
From what I saw in the first diagnostics file you gave me in https://github.com/Crisicus/maestro_mcz/issues/35#issuecomment-1528963397.
"UniqueCode": "**REDACTED**",
 "sm_sn": "",

The one with the empty string is not good 😄

**Comment by RickType** [comment]
So, I changed the polling intervall today to 60 Sekonds and the stove showed up twice.
Additionally the stove is losing it's Wifi connection every 12-24 hours. Without the integration enabled it was running for 3 month with just one connection loss. Tomorrow I get a new mainboard for the stove. Let's see if it still loses the connection.

**Comment by Robbe-B** [comment]
@RickType,
We are aware of this wifi problem, unfortunately there is not much we can do about this, since this is a firmware problem.
Did you saw https://github.com/Crisicus/maestro_mcz/issues/20 ?
Try disabeling the bluetooth, the problem should be better after that.

**Comment by RickType** [comment]
Thanks, will set the polling rate to a higher value. I can't switch Bluetooth off. I can set the preferred connection method in the app, but both interfaces are always on.
I need a reliable connection. My use case is that the central gas heater will be switched on (via Shelly), when the stove is running dry. This is mainly when we are on holidays during winter time.
Wifi

**Comment by Crisicus** [comment]
> Thanks, will set the polling rate to a higher value. I can't switch Bluetooth off. I can set the preferred connection method in the app, but both interfaces are always on.
> 
> I need a reliable connection. My use case is that the central gas heater will be switched on (via Shelly), when the stove is running dry. This is mainly when we are on holidays during winter time.
> 
> Wifi
> 
> 

You have to turn Bluetooth of physically on the stove by holding + and - for 10 seconds. The stove then beeps and the Bluetooth icon disappears

**Comment by Robbe-B** [comment]
@RickType, 
Indeed as @Crisicus, ...
image

**Comment by RickType** [comment]
Sorry, was checking only the app. But sure, you can disable it on the panel itself.

**Comment by RickType** [comment]
Hi,

I can confirm that this workaround works. I dissabled BT and set the refresh intervall to 3 minutes.
Until now no disconnect.

@Robbe-B : Will send you the diagnostics and the screenshot soon. Tomorrow I'll install the heatpump for the tap water, afterwards I'll take care about the MCZ again... ;-)

**Pull request merged**
